### ISSUE TITLE
Missing build steps lead to crashes during application execution

### ISSUE THREAD

**Issue by leandrosansilva** [ngi-nix/lightmeter#1]
The original build makefile includes the following steps, required to the application behave properly when executed: `static_www`
`domain_mapping_list` and `po2go`.

Currently only `static_www` is executed in the preBuild phase on the default.nix file.

- `static_www` adds all html pages and web other resources to the application binary.
- `domain_mapping_list`, whose lack explains the current crashes, attaches a static domain mapping table to the application binary. When not executed, such table is `nil`, which when dereferenced, makes the application crash.
- `po2go` enable internationalization on the application ui. Without it, the application supports only English.

Please have a look how such steps are executed in this abandoned try to package lightmeter for nixos, which  execute the build steps properly;

https://gitlab.com/donutloop/nixos-lightmeter/-/blob/feature/nixos_controlcenter/nixos/pkgs/controlcenter/default.nix

```
buildPhase = ''
  go generate -tags="release" ./staticdata
  go generate ./domainmapping
  go generate ./po
  go install -tags="release"
  '';


```

Regards,
Leandro

**Comment by eadwu** [comment]
Now building with `make release` since `vendor` is included upstream, which should make tracking along master easier for the future.
