### ISSUE TITLE
Build instructions are missing 

### ISSUE THREAD

**Issue by donutloop** [ngi-nix/lightmeter#2]
Please provide a sufficient set of build instructions for local and production environments included in a Readme.md. That everyone is able to build the module and package inside of this repository.

Regards,
Marcel

**Comment by eadwu** [comment]
Sorry about the delay, turns out I wasn't pinged about the issue through GitHub. Added the README, which should cover most of the use cases intended of this repo if not all.

**Comment by donutloop** [comment]
looks good to me, Thanks!
